












- hosts: all
  vars:
    variable_name:   #this is dictionary
      id: 1234321
      name: balu  
    variable_2: variable value 2  # this is variable
    variable_3: variable value 3         
  tasks:
  - name: this playbook is about to understanting dictionary and variables difference
    debug:
      msg: "{{ variable_name.id }}  and {{ variable_name.name }},  and also variable_2 is:::::::::  {{ variable_2 }}||||||||||||||  variable_3 is:::::::::::::{{ variable_3 }}     "

