



---

- name: nginx playbook jinja2 test
  hosts: all
  tasks:
    - name: installing nginx
      apt: 
        name: nginx
        state: latest
    - name: push a new intex.html config file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: 0775
